name: Test Installer

on:
  pull_request:
    paths:
      - "bootstrap/**"
      - ".github/scripts/test-installer.sh"
      - ".github/workflows/test-installer.yml"
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo bash .github/scripts/test-installer.sh
